FROM --platform=$BUILDPLATFORM golang:1.22 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG TARGETOS=linux
ARG TARGETARCH=amd64
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o /out/pantech-csi ./cmd/pantech-csi

FROM debian:12-slim
RUN apt-get update \
  && apt-get install -y --no-install-recommends e2fsprogs xfsprogs util-linux ca-certificates \
  && rm -rf /var/lib/apt/lists/*
COPY --from=build /out/pantech-csi /pantech-csi
ENTRYPOINT ["/pantech-csi"]
